<a href="https://colab.research.google.com/github/UMB200/pytorch_projects/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [50]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [51]:

# Create random tensor
import torch
random_tensor_7 = torch.rand(7, 7)
print(f"Tensor 7: \n{random_tensor_7}")



Tensor 7: 
tensor([[0.0223, 0.1689, 0.2939, 0.5185, 0.6977, 0.8000, 0.1610],
        [0.2823, 0.6816, 0.9152, 0.3971, 0.8742, 0.4194, 0.5529],
        [0.9527, 0.0362, 0.1852, 0.3734, 0.3051, 0.9320, 0.1759],
        [0.2698, 0.1507, 0.0317, 0.2081, 0.9298, 0.7231, 0.7423],
        [0.5263, 0.2437, 0.5846, 0.0332, 0.1387, 0.2422, 0.8155],
        [0.7932, 0.2783, 0.4820, 0.8198, 0.9971, 0.6984, 0.5675],
        [0.8352, 0.2056, 0.5932, 0.1123, 0.1535, 0.2417, 0.7262]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [52]:
# Create another random tensor
random_tensor_8 = torch.rand(1, 7)
print(f"Tensor 8: \n{random_tensor_8}")
transposed_tensor_8 = random_tensor_8.T

# Perform matrix multiplication
output = torch.mm(random_tensor_7, transposed_tensor_8)
print(f"\nTensor 7 x 8: \n{output, output.size()}")


Tensor 8: 
tensor([[0.7011, 0.2038, 0.6511, 0.7745, 0.4369, 0.5191, 0.6159]])

Tensor 7 x 8: 
(tensor([[1.4622],
        [2.1803],
        [1.8105],
        [1.6405],
        [1.5135],
        [2.7092],
        [1.7404]]), torch.Size([7, 1]))


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [53]:
# Set manual seed
import torch

RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED) #Set random seed is needed for each tensor
random_tensor_7

torch.manual_seed(RANDOM_SEED) #Set random seed is needed for each tensor
random_tensor_8
transposed_tensor_8 = random_tensor_8.T

# Matrix multiply tensors
torch.mm(random_tensor_7, transposed_tensor_8)

tensor([[1.4622],
        [2.1803],
        [1.8105],
        [1.6405],
        [1.5135],
        [2.7092],
        [1.7404]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [54]:
# Set random seed on the GPU
import torch
RANDOM_SEED_GPU = 1234
torch.cuda.manual_seed_all(RANDOM_SEED_GPU)
random_tensor_7
torch.manual_seed(RANDOM_SEED) #Set random seed is needed for each tensor
random_tensor_8
transposed_tensor_8 = random_tensor_8.T

# Matrix multiply tensors
torch.mm(random_tensor_7, transposed_tensor_8)


tensor([[1.4622],
        [2.1803],
        [1.8105],
        [1.6405],
        [1.5135],
        [2.7092],
        [1.7404]])


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [55]:
# Set random seed
import torch
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)


# Check for access to GPU
cuda_device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
random_tensor_2_3_A = torch.rand(2, 3)
random_tensor_2_3_B = torch.rand(2, 3)
tensor_A_on_gpu = random_tensor_2_3_A.to(cuda_device)
tensor_B_on_gpu = random_tensor_2_3_B.to(cuda_device)

print(f"Device: {torch.device(cuda_device)}")
print(f"Tensor A: {tensor_A_on_gpu}")
print(f"Tensor B: {tensor_B_on_gpu}")

Device: cuda
Tensor A: tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]], device='cuda:0')
Tensor B: tensor([[0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [66]:
# Perform matmul on tensor_A and tensor_B
transposed_tensor_B2 = tensor_B_on_gpu.T
output7 = torch.mm(tensor_A_on_gpu, transposed_tensor_B2)
print(f"Tensor output {output7, output7.size()}")

Tensor output (tensor([[0.9722, 0.6174],
        [0.6292, 0.4455]], device='cuda:0'), torch.Size([2, 2]))


### 8. Find the maximum and minimum values of the output of 7.

In [67]:
# Find max
print(f"Max of tensor in step 7: {output7.max()}")
# Find min
print(f"Min of tensor in step 7: {output7.min()}")


Max of tensor in step 7: 0.9721932411193848
Min of tensor in step 7: 0.4454618990421295


### 9. Find the maximum and minimum index values of the output of 7.

In [73]:
# get the tensor
print(f"Tensor output: \n{output7}")
# Find arg max
print(f"Index of max value of tensor in step 7: {torch.argmax(output7)}")
# Find arg min
print(f"Index of min value of tensor in step 7: {torch.argmin(output7)}")


Tensor output: 
tensor([[0.9722, 0.6174],
        [0.6292, 0.4455]], device='cuda:0')
Index of max value of tensor in step 7: 0
Index of min value of tensor in step 7: 3



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [77]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
tensor10 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor10_reduced = torch.squeeze(tensor10)


# Print out tensors and their shapes
print(f"Initial tensor: {tensor10, tensor10.shape}")

print(f"Reduced tensor: {tensor10_reduced, tensor10_reduced.shape}")

Initial tensor: (tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]))
Reduced tensor: (tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]))
